# Rename this file to secrets.toml and place it inside a folder named .streamlit
# For local testing only. For Streamlit Cloud, use the UI to add secrets.

OPENAI_API_KEY = "your-openai-api-key-here"
